### ISSUE TITLE
I cant get it to work.

### ISSUE THREAD

**Issue by x-j0nnay-x** [Lucrecious/Minecraft-Modding-Armor-Tutorial#1]
Im using 1.7.10 and i cant get it to work

**Comment by x-j0nnay-x** [comment]
Crash report
`---- Minecraft Crash Report ----
// My bad.

Time: 5/25/16 6:34 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
    at com.DefineCraft.item.HellStone.HellStoneArmorFullModel.<init>(HellStoneArmorFullModel.java:39)
    at com.DefineCraft.common.Proxy.ClientProxy.register_renderers(ClientProxy.java:18)
    at com.DefineCraft.common.DefineCraftMod.preinit(DefineCraftMod.java:150)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.startGame(Minecraft.java:597)
    at net.minecraft.client.Minecraft.run(Minecraft.java:942)
    at net.minecraft.client.main.Main.main(Main.java:164)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
    at GradleStart.main(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as 

## follows:

## 

Head --
Stacktrace:

at com.DefineCraft.item.HellStone.HellStoneArmorFullModel.<init>(HellStoneArmorFullModel.java:39)

at com.DefineCraft.common.Proxy.ClientProxy.register_renderers(ClientProxy.java:18)

at com.DefineCraft.common.DefineCraftMod.preinit(DefineCraftMod.java:150)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

at java.lang.reflect.Method.invoke(Unknown Source)

at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

at java.lang.reflect.Method.invoke(Unknown Source)

at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)

at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)

at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)

at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)

at com.google.common.eventbus.EventBus.post(EventBus.java:275)

at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)

at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

at java.lang.reflect.Method.invoke(Unknown Source)

at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)

at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)

at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)

at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)

at com.google.common.eventbus.EventBus.post(EventBus.java:275)

at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)

at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)

at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)

at net.minecraft.client.Minecraft.startGame(Minecraft.java:597)

## -- Initialization 

Details:
Stacktrace:

at net.minecraft.client.Minecraft.run(Minecraft.java:942)

at net.minecraft.client.main.Main.main(Main.java:164)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

at java.lang.reflect.Method.invoke(Unknown Source)

at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)

at GradleStart.main(Unknown Source)

-- System Details
 --
Details:

Minecraft Version: 1.7.10

Operating System: Windows 10 (amd64) version 10.0

Java Version: 1.8.0_91, Oracle Corporation

Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

Memory: 723009920 bytes (689 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
    J
VM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used

IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0

FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 5 mods loaded, 5 mods active

States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

```
UCHI    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)

UCHI    FML{7.10.99.99} [Forge Mod Loader] (forgeSrc-1.7.10-10.13.4.1448-1.7.10.jar)

UCHI    Forge{10.13.4.1448} [Minecraft Forge] (forgeSrc-1.7.10-10.13.4.1448-1.7.10.jar) 

UCHE    DefineCraft{V 0.0.8} [DefineCraft] (bin)

UCHI    tutorialmod{1.7.1.0.0.1} [Tutorial Mod] (bin) 
```

GL info: 
' Vendor: 'ATI Technologies Inc.'
 Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004'
 Renderer: 'AMD Radeon HD 6670'

Launched Version: 1.7.10

LWJGL: 2.9.1

OpenGL: AMD Radeon HD 6670 GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1004, ATI Technologies Inc.

```
GL Caps: Using GL 1.3 multitexturing.
```

Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.

```
Anisotropic filtering is supported and maximum anisotropy is 16.
```

Shaders are available because OpenGL 2.1 is supported.

Is Modded: Definitely; Client brand changed to 'fml,forge'

Type: Client (map_client.txt)
    Resource Packs: []

Current Language: English (US)

Profiler Position: N/A (disabled)

Vec3 Pool Size: 0 (0 bytes; 0 MB) 
allocated, 0 (0 bytes; 0 MB) used

Anisotropic Filtering: Off (1)`

**Comment by x-j0nnay-x** [comment]
I got that problem fixed but now its not rendering the Head model right

**Comment by Lucrecious** [comment]
Like I said in the video, there are differences between what you see in techne and the way Minecraft's game library handles models. Unfortunately, from what I understand, you just need to play around with the values. Good luck.

**Comment by x-j0nnay-x** [comment]
Ya it works with i do not add the link form one peace to another, like if i link the base to the head then up from there it goes in to a visual glitch and makes it look like i have 100 cubes  instead of the 5. i dont know if thats just my coding it or what, before i add the link its all working and looking correct but then it dose not move with my head.

**Comment by Lucrecious** [comment]
I see. I'd need to see the entirety of your code to actually help with the problem, but I haven't done any Minecraft modding in over a year - it might be better to post on the Minecraft modding forum. Also, this doesn't seem like an issue on my side of things, seems more like an issue on your side - this code works as intended from what I recall.

**Comment by x-j0nnay-x** [comment]
It's not an issue with your side, it is my code. But the chest armor works and that's the main thing I wanted. I needed to add wings to my guy. Adding the horns was just to see if I could
